import type { ThemeColors } from '@/constants/theme';
import { FontSize, Layout, LineHeight, Opacity, Radius, Spacing } from '@/constants/layout';
import { StyleSheet } from 'react-native';

/**
 * All shared screen/component styles derived from the active color scheme.
 * Edit `layout.ts` for spacing/type; edit `Palette` in `theme.ts` for colors.
 */
export function createThemedStyles(c: ThemeColors) {
  return StyleSheet.create({
    /** Login, setup-dog, boot — same shell (padding, gap, background). */
    formFlowScreen: {
      flex: 1,
      padding: Spacing.xl,
      gap: Spacing.md,
      justifyContent: 'center',
      backgroundColor: c.background,
    },
    /** Centers spinner on boot without affecting full-width fields on other flow screens. */
    flowBootInner: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    flowBootCaption: {
      marginTop: Spacing.lg,
      fontSize: FontSize.callout,
      fontWeight: '600',
      textAlign: 'center',
      color: c.text,
      opacity: Opacity.subtitle,
    },
    screenSectionTitle: {
      fontSize: FontSize.section,
      fontWeight: '700',
      textAlign: 'center',
      color: c.text,
    },
    fieldLabel: {
      fontSize: FontSize.label,
      fontWeight: '600',
      color: c.text,
    },
    textField: {
      borderWidth: 0,
      borderColor: c.inputBorder,
      borderRadius: Radius.sm,
      padding: Spacing.md,
      fontSize: FontSize.body,
      color: c.text,
      backgroundColor: c.inputBackground,
    },
    /** Universal filled CTA — colour from `buttonPrimaryBackground` / `buttonPrimaryText`. */
    primaryButton: {
      paddingVertical: Spacing.buttonPaddingY,
      paddingHorizontal: Spacing.md,
      borderRadius: Radius.md,
      alignItems: 'center',
    },
    ghostButtonOpacity: {
      opacity: Opacity.ghostButton,
    },
    buttonLabel: {
      fontSize: FontSize.body,
      fontWeight: '600',
    },
    ghostButtonLabel: {
      fontSize: FontSize.body,
      fontWeight: '600',
    },
    setupHeroImage: {
      width: '100%',
      height: Layout.setupImageHeight,
      borderRadius: Radius.lg,
      alignSelf: 'center',
    },
    disabled: {
      opacity: Opacity.disabled,
    },

    tabScreen: {
      flex: 1,
      backgroundColor: c.background,
    },
    settingsContent: {
      flex: 1,
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing.xl,
      gap: Spacing.lg,
    },
    settingsTitle: {
      marginBottom: 0,
    },
    settingsSubtitle: {
      opacity: Opacity.subtitle,
    },
    settingsCard: {
      borderRadius: Radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.inputBorder,
      backgroundColor: c.background,
      padding: Spacing.lg,
      marginTop: Spacing.sm,
    },
    settingsCardLabel: {
      fontSize: FontSize.caption,
      fontWeight: '600',
      color: c.textMuted,
    },
    settingsCardLabelSpaced: {
      marginTop: Spacing.md,
    },
    settingsCardValue: {
      fontSize: FontSize.md,
      marginTop: Spacing.xs,
      color: c.text,
    },
    outlineButton: {
      marginTop: Spacing.sm,
      paddingVertical: Spacing.buttonPaddingY,
      borderRadius: Radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.buttonPrimaryBackground,
      backgroundColor: c.background,
      alignItems: 'center',
    },
    outlineButtonLabel: {
      fontSize: FontSize.body,
      fontWeight: '600',
      color: c.buttonPrimaryBackground,
    },

    gameRoot: {
      flex: 1,
      position: 'relative',
      overflow: 'hidden',
      backgroundColor: c.sceneSkyBottom,
    },
    /** Full-bleed scene behind HUD / title / health (pointerEvents none). */
    gameBackgroundLayer: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 0,
    },
    /** Foreground dashboard chrome above the SVG. */
    gameContentLayer: {
      flex: 1,
      zIndex: 1,
      paddingHorizontal: Spacing.gameScreenPaddingX,
      paddingBottom: Spacing.lg,
    },
    hudRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xl,
      gap: Spacing.md,
    },
    hudPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: Radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.hudPillBackground,
      flex: 1,
      maxWidth: '48%',
    },
    hudValue: {
      fontSize: FontSize.lg,
      fontWeight: '700',
      color: c.text,
    },
    hudRowCompact: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
      gap: Spacing.sm,
    },
    hudPillCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: Radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.hudPillBackground,
      flex: 1,
      maxWidth: '48%',
    },
    hudValueCompact: {
      fontSize: FontSize.callout,
      fontWeight: '700',
      color: c.text,
    },
    hudRowCurrencies: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      marginBottom: Spacing.sm,
    },
    hudPillShort: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingVertical: 5,
      paddingHorizontal: 9,
      borderRadius: Radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.hudPillBackground,
      minWidth: 94,
    },
    hudPillAddButton: {
      width: 22,
      height: 22,
      borderRadius: Radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gameTopHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: Spacing.sm,
      marginBottom: Spacing.sm,
      gap: Spacing.sm,
    },
    profilePawButton: {
      width: 44,
      height: 44,
      borderRadius: Radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.hudPillBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dogTitle: {
      fontSize: FontSize.section,
      fontWeight: '700',
      textAlign: 'center',
      marginBottom: Spacing.md,
      color: c.text,
      textShadowColor: 'rgba(0,0,0,0.25)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    /** Fills space under title; left column holds circular stat HUD. */
    gameMainBody: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    statRingsColumn: {
      gap: Spacing.lg,
      alignItems: 'center',
    },
    statRingItem: {
      alignItems: 'center',
      gap: Spacing.xs,
    },
    statRingWrap: {
      width: Layout.statRingSize,
      height: Layout.statRingSize,
      justifyContent: 'center',
      alignItems: 'center',
    },
    statRingPercent: {
      position: 'absolute',
      fontSize: FontSize.callout,
      fontWeight: '700',
      color: c.healthLabel,
      textAlign: 'center',
      textShadowColor: 'rgba(0,0,0,0.45)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    statRingLabel: {
      fontSize: FontSize.caption,
      fontWeight: '600',
      color: c.healthLabel,
      textAlign: 'center',
      maxWidth: Layout.statRingSize + Spacing.md,
      textShadowColor: 'rgba(0,0,0,0.35)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },

    gameTabBar: {
      flexDirection: 'row',
      zIndex: 2,
      elevation: 10,
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.sm,
      marginHorizontal: Spacing.lg,
      marginBottom: Spacing.sm,
      borderRadius: Radius.xl,
      backgroundColor: c.hudPillBackground,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 14,
    },
    gameTabItem: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 44,
      height: 44,
      borderRadius: Radius.pill,
      borderWidth: 0,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
    },
    gameTabItemActive: {
      backgroundColor: c.inputBackground,
      borderColor: 'transparent',
    },
    gameTabItemPressed: {
      opacity: Opacity.ghostButton,
    },
    gameTabGaugeItem: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 44,
      height: 44,
      borderRadius: Radius.pill,
      borderWidth: 0,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
      overflow: 'hidden',
      position: 'relative',
    },
    gameTabGaugeItemFeatured: {
      width: 62,
      height: 62,
      marginTop: -30,
      borderRadius: Radius.lg,
      borderWidth: 0,
      borderColor: 'transparent',
      backgroundColor: c.buttonPrimaryBackground,
      transform: [{ rotate: '45deg' }],
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 12,
      elevation: 12,
    },
    gameTabGaugeFillFood: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: c.foodBarFill,
      opacity: 0.45,
    },
    gameTabGaugeFillWater: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: c.waterBarFill,
      opacity: 0.45,
    },
    gameTabGaugeIcon: {
      zIndex: 1,
    },
    gameTabGaugeIconFeatured: {
      transform: [{ rotate: '-45deg' }],
    },
    gameQuickModalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.35)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
    },
    gameQuickModalCard: {
      width: '100%',
      borderRadius: Radius.xl,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.hudPillBackground,
      padding: Spacing.lg,
      gap: Spacing.md,
    },
    gameQuickModalHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    gameQuickModalTitle: {
      fontSize: FontSize.md,
      fontWeight: '700',
      color: c.text,
    },
    gameQuickModalInfoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: Spacing.xs,
    },
    gameQuickModalInfoValue: {
      fontSize: FontSize.lg,
      fontWeight: '700',
      color: c.text,
    },
    shopSegmentWrap: {
      flexDirection: 'row',
      gap: Spacing.sm,
      padding: Spacing.xs,
      borderRadius: Radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.inputBorder,
      backgroundColor: c.hudPillBackground,
    },
    shopSegmentButton: {
      flex: 1,
      borderRadius: Radius.md,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    shopSegmentButtonActive: {
      backgroundColor: c.buttonPrimaryBackground,
    },
    shopSegmentButtonPressed: {
      opacity: Opacity.ghostButton,
    },
    shopSegmentLabel: {
      fontSize: FontSize.body,
      fontWeight: '700',
      color: c.buttonPrimaryBackground,
    },
    shopSegmentLabelActive: {
      color: c.buttonPrimaryText,
    },
    shopWalletRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.sm,
    },
    shopWalletPill: {
      flex: 1,
      borderRadius: Radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.hudPillBorder,
      backgroundColor: c.hudPillBackground,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
    },
    shopWalletLabel: {
      fontSize: FontSize.caption,
      fontWeight: '600',
      color: c.textMuted,
    },
    shopWalletValue: {
      marginTop: Spacing.xs,
      fontSize: FontSize.lg,
      fontWeight: '700',
      color: c.text,
    },
    shopList: {
      gap: Spacing.md,
      paddingBottom: Spacing.xl,
    },
    shopCard: {
      borderRadius: Radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.inputBorder,
      backgroundColor: c.background,
      padding: Spacing.lg,
      gap: Spacing.xs,
    },
    shopCardActive: {
      borderColor: c.buttonPrimaryBackground,
      backgroundColor: c.hudPillBackground,
    },
    shopCardTitle: {
      fontSize: FontSize.md,
      fontWeight: '700',
      color: c.text,
    },
    shopCardPrice: {
      fontSize: FontSize.callout,
      fontWeight: '600',
      color: c.textMuted,
    },
    shopCardAction: {
      marginTop: Spacing.sm,
    },
    shopCardActionDisabled: {
      opacity: Opacity.disabled,
    },

    modalContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.modalPadding,
    },
    modalLink: {
      marginTop: Spacing.modalLinkMarginTop,
      paddingVertical: Spacing.modalLinkPaddingY,
    },
  });
}

export type ThemedStyles = ReturnType<typeof createThemedStyles>;
